### ISSUE TITLE
Possible Faulty Tests

### ISSUE THREAD

**Issue by marknosal** [learn-co-curriculum/react-hooks-use-effect-lab#1]
### Canvas Link

https://learning.flatironschool.com/courses/6191/assignments/228671?module_item_id=534056

### Concern

I think the tests are faulty.  I had aTC check it out and they said my code was fine (we tested with multiple console.logs).  The deliverables were working as intended.  I even copy/pasted the solution as well and it failed that too.

### Additional Context

![image](https://user-images.githubusercontent.com/118954734/230217412-55f733b3-ec68-467f-a592-638afc78bf97.png)

**Comment by lizbur10** [comment]
Hi @marknosal ! Thanks for bringing this to our attention. The `Question.test.js` file has been updated which should fix the problem.

Thanks for contributing to the Flatiron curriculum 💙
